import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {brandLine,customFonts} from '../src/content.js';
const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();const base=process.env.TEST_URL||'http://localhost:5173';await p.goto(base);await p.waitForFunction(()=>!document.querySelector('.brand-intro'));
assert.equal(await p.locator('.scene-cat').count(),0);assert.equal(await p.locator('h1').textContent(),brandLine);assert.equal(await p.locator('h1 .title-period').count(),2);assert.equal(await p.locator('h1 .punctuated-word').first().evaluate(e=>getComputedStyle(e).color),'rgb(29, 27, 24)');assert.equal(await p.locator('h1 .title-period').first().evaluate(e=>getComputedStyle(e).color),'rgb(53, 89, 74)');assert.equal(await p.locator('.hero-copy').evaluate(e=>getComputedStyle(e).backgroundImage),'none');assert.notEqual(await p.locator('.hero-environment').evaluate(e=>getComputedStyle(e).clipPath),'none');
await p.getByRole('button',{name:'Pause ambient motion'}).click();assert.equal(await p.locator('.ambient-steam i').first().evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.ambient-steam i').first().evaluate(e=>getComputedStyle(e).animationName),'none');
for(const id of ['overview','foundations','logos','colour','typography','voice']){await p.goto(base+'/#'+id);await p.evaluate(()=>document.fonts.ready);assert.ok(!/In good company|Chapter \d/i.test(await p.locator('main').innerText()));assert.equal(await p.locator('main h1 .title-period').count(),id==='overview'?2:1);await p.screenshot({path:`.playwright/v5-${id}-desktop.png`,fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+id);await p.screenshot({path:`.playwright/v5-${id}-mobile.png`,fullPage:true});await p.setViewportSize({width:1440,height:1000})}
await p.goto(base+'/#colour');assert.equal(await p.locator('.badge.approved').count(),1);assert.equal(await p.getByText('Interface colours.',{exact:true}).count(),1);await p.getByText('Developer details',{exact:true}).click();assert.ok(await p.getByText('Proposed functional tokens:',{exact:false}).count());
await p.goto(base+'/#logos');for(const [name,colour] of [['Cream','rgb(255, 248, 240)'],['Sage','rgb(167, 181, 158)'],['Orange','rgb(240, 106, 33)']]){await p.getByRole('button',{name,exact:true}).click();assert.equal(await p.locator('.logo-specimen').evaluate(e=>getComputedStyle(e).backgroundColor),colour);assert.equal(await p.locator('.logo-specimen .brand-word').evaluate(e=>getComputedStyle(e).color),'rgb(29, 27, 24)')}
await p.goto(base+'/#typography');for(const f of customFonts){assert.ok(await p.locator(`a[href="${f.path}"]`).count());let r=await c.request.get(base+f.path);assert.equal(r.status(),200);assert.ok((await r.body()).length>14000)}
console.log('PASS: new catchphrase, title punctuation, removed decorative cat, crisp clipping, pause/reduced motion, six pages desktop/mobile, single palette badge, logo background switcher, custom font downloads.');await b.close();
