import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {brandLine,allFonts,brandStatuses} from '../src/content.js';import fs from 'node:fs';
const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();const base=process.env.TEST_URL||'http://localhost:5173';await p.goto(base);await p.waitForFunction(()=>!document.querySelector('.brand-intro'));
assert.equal(await p.locator('.scene-cat').count(),0);assert.equal(await p.locator('h1').textContent(),'Better Together.');assert.equal(await p.locator('h1 .title-period').count(),1);assert.equal(await p.locator('h1 .title-period').evaluate(e=>getComputedStyle(e).color),'rgb(240, 106, 33)');assert.equal(await p.locator('.hero-copy').evaluate(e=>getComputedStyle(e).backgroundImage),'none');assert.equal(await p.locator('.hero-environment').evaluate(e=>getComputedStyle(e).clipPath),'none');assert.equal(await p.locator('.courtyard-source').getAttribute('mask'),'url(#courtyard-art-mask)');assert.equal(await p.locator('#courtyard-art-mask image').getAttribute('href'),'/courtyard-mask.svg');
await p.getByRole('button',{name:'Pause ambient motion'}).click();assert.equal(await p.locator('.courtyard-scene').getAttribute('data-motion-state'),'paused');const frozen=await p.locator('.steam-wisp').first().getAttribute('transform');await p.waitForTimeout(150);assert.equal(await p.locator('.steam-wisp').first().getAttribute('transform'),frozen);await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.mug-steam').evaluate(e=>getComputedStyle(e).display),'none');
for(const id of ['overview','foundations','logos','colour','typography','voice']){await p.goto(base+'/#'+id);await p.evaluate(()=>document.fonts.ready);assert.ok(!/In good company|Chapter \d/i.test(await p.locator('main').innerText()));assert.equal(await p.locator('main h1 .title-period').count(),1);await p.screenshot({path:`.playwright/v6-${id}-desktop.png`,fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+id);await p.screenshot({path:`.playwright/v6-${id}-mobile.png`,fullPage:true});await p.setViewportSize({width:1440,height:1000})}
await p.goto(base+'/#colour');assert.equal(await p.locator('.reference-title .badge').first().textContent(),'Proposed');assert.equal(await p.getByText('Interface colours.',{exact:true}).count(),0);assert.equal(await p.locator('.interface-colours').count(),0);
await p.goto(base+'/#logos');assert.equal(await p.locator('.logo-background').first().getAttribute('data-logo-bg'),'#F06A21');assert.equal(await p.getByRole('button',{name:'Orange',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.logo-preview').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(240, 106, 33)');for(const [name,colour] of [['Cream','rgb(255, 248, 240)'],['Sage','rgb(167, 181, 158)'],['Orange','rgb(240, 106, 33)']]){await p.getByRole('button',{name,exact:true}).click();assert.equal(await p.locator('.logo-preview').evaluate(e=>getComputedStyle(e).backgroundColor),colour);assert.equal(await p.locator('.logo-specimen .brand-word').evaluate(e=>getComputedStyle(e).color),'rgb(29, 27, 24)')}
await p.getByRole('button',{name:'Soft ink',exact:true}).focus();await p.getByRole('button',{name:'Soft ink',exact:true}).press('Enter');assert.equal(await p.locator('.logo-preview').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(29, 27, 24)');assert.equal(await p.locator('.logo-specimen .brand-word').evaluate(e=>getComputedStyle(e).color),'rgb(255, 248, 240)');assert.equal(await p.locator('.header-logo .brand-word').evaluate(e=>getComputedStyle(e).color),'rgb(29, 27, 24)');assert.equal(await p.locator('.logo-specimen img').getAttribute('src'),'/brand/mojo-cat-transparent.svg');assert.equal(await p.locator('.logo-instruction').innerText(),'Use the cream wordmark on a Soft ink background.');
await p.getByRole('button',{name:'Cream',exact:true}).click();assert.equal(await p.locator('.logo-specimen .brand-word').evaluate(e=>getComputedStyle(e).color),'rgb(29, 27, 24)');assert.equal(await p.locator('.logo-preview-footer button[aria-pressed=true]').count(),1);
assert.deepEqual(await p.locator('.key-guidance').allTextContents(),['Keep the cat to the left of mojo.','Do not stretch, rotate, or rearrange the logo.']);
await p.goto(base+'/#typography');assert.deepEqual(await p.locator('.font-specimen-row h2').allTextContents(),['Mojo Draft','Mojo Refined','Inter']);assert.deepEqual(await p.locator('.font-sample').allTextContents(),[brandLine,brandLine,brandLine]);assert.ok(!/version|0\.200|0\.601|100–900/.test(await p.locator('.font-specimens').innerText()));assert.equal(await p.locator('details').getAttribute('open'),null);
for(const f of allFonts){assert.equal(await p.locator(`.font-specimens a[href="${f.path}"]`).count(),1);let r=await c.request.get(base+f.path);assert.equal(r.status(),200);assert.deepEqual(await r.body(),fs.readFileSync('public'+f.source))}
const fontDownload=p.waitForEvent('download');await p.getByRole('link',{name:'Download all fonts'}).click();assert.equal((await fontDownload).suggestedFilename(),'mojo-fonts.zip');
await p.goto(base+'/#logos');assert.equal(await p.locator('.logo-lab .badge').innerText(),brandStatuses.signature);assert.equal(await p.locator('.mascot-animations .badge').innerText(),brandStatuses.animations);assert.equal(await p.locator('.mascot-animations a,.mascot-animations button').count(),0);
await p.goto(base+'/#colour');assert.equal(await p.locator('.swatch').count(),5);assert.deepEqual(await p.locator('.palette-pending .badge').allTextContents(),[brandStatuses.secondaryPalette,brandStatuses.tertiaryPalette]);assert.equal(await p.locator('.palette-pending .paint').count(),0);
await p.goto(base+'/#foundations');assert.equal(await p.locator('.strategic-pending').innerText(),'We’re waiting for the product to be finalized before fully approving the brand foundations.');
for(const width of [320,390,768]){await p.setViewportSize({width,height:900});await p.goto(base);assert.ok(await p.evaluate(()=>document.querySelector('.courtyard-scene').getBoundingClientRect().top>=document.querySelector('.hero-foot').getBoundingClientRect().bottom),'Artwork must stay below text on mobile');assert.ok(!/02 \/ MASCOT|06 \/ PROPOSED|MADE FOR EVERY KIND|ORIGINAL CONCEPT/.test(await p.locator('main').innerText()));assert.ok(await p.locator('#global-search').isVisible());assert.ok(await p.locator('.top-guide').isVisible());assert.equal(await p.locator('.top-guide').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(53, 89, 74)');await p.locator('#search-input').fill('signature');await p.locator('#search-input').press('Enter');await p.waitForSelector('.search-results');assert.ok(await p.locator('.search-results a[href="#foundations"]').count());await p.locator('.top-guide').click();assert.ok(p.url().endsWith('/downloads/quick-guide.html'));await p.getByRole('heading',{name:'Primary colour palette',exact:true}).waitFor();assert.ok(await p.getByRole('heading',{name:'Primary colour palette',exact:true}).count());assert.equal(await p.locator('[data-status=signature]').innerText(),brandStatuses.signature);assert.equal(await p.locator('[data-status=primaryPalette]').innerText(),brandStatuses.primaryPalette)}
console.log('PASS: title punctuation, artwork mask, ambient motion, six pages desktop/mobile, shared statuses, three font specimens, four exact font downloads, all-fonts ZIP download, mobile header search and Quick guide.');await b.close();
