from pathlib import Path
import html,zipfile,shutil
root=Path(__file__).resolve().parents[1]; out=root/'public/downloads';out.mkdir(exist_ok=True)
items=[('social','Social announcement','Good ideas.\nGreat company.'),('demo','Product demo','Show the idea.\nKeep it simple.'),('spotlight','Creation spotlight','Made with care.\nShared with Mojo.'),('recruitment','Creator recruitment','Make room\nfor your ideas.'),('campus','Campus event','A gathering\nof good ideas.'),('partnership','Partnership brief','Let’s make\nsomething together.')]
for i,(key,label,title) in enumerate(items):
 bg='#35594A' if i%2 else '#FFF8F0';fg='#FFF8F0' if i%2 else '#1D1B18'
 lines=''.join(f'<tspan x="80" dy="{0 if n==0 else 100}">{html.escape(s)}</tspan>' for n,s in enumerate(title.split('\n')))
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 1080 1080"><title>{label} — proposed editable starter</title><rect width="1080" height="1080" fill="{bg}"/><rect x="80" y="80" width="64" height="16" fill="#F06A21"/><text x="80" y="165" font-family="Arial,sans-serif" font-size="20" letter-spacing="4" fill="{fg}">MOJO / {label.upper()}</text><text x="80" y="360" font-family="Georgia,serif" font-size="88" fill="{fg}">{lines}</text><rect x="80" y="550" width="920" height="260" fill="#A7B59E"/><text x="540" y="690" text-anchor="middle" font-family="Arial,sans-serif" font-size="24" fill="#1D1B18">Replace with approved image or event details</text><text x="80" y="920" font-family="Arial,sans-serif" font-size="24" fill="{fg}">Add your approved copy here.</text><text x="80" y="1010" font-family="Arial,sans-serif" font-size="16" fill="{fg}">PROPOSED / V0.2 · Portable SVG uses system fonts · Install Mojo fonts for branded editing</text></svg>'''
 (out/f'{key}.svg').write_text(svg)
style='@font-face{font-family:MojoPixel;src:url(../fonts/MojoPixelSerif-Draft-Regular.ttf)}@font-face{font-family:MojoRefined;src:url(../fonts/MojoSerif-Refined-Regular.ttf)}@font-face{font-family:Inter;src:url(../fonts/Inter-Variable.ttf);font-weight:100 900}@font-face{font-family:Inter;src:url(../fonts/Inter-Italic-Variable.ttf);font-weight:100 900;font-style:italic}body{margin:0;background:#FFF8F0;color:#1D1B18;font:16px/1.6 Inter,Arial,sans-serif}main{max-width:900px;margin:40px auto;padding:40px}h1{font-family:MojoPixel,Georgia,serif;font-weight:400}h2{font-family:MojoRefined,Georgia,serif;font-weight:400}h1{font-size:52px}section{padding:35px;border:1px solid #A7B59E;margin:25px 0}small{color:#35594A}button{padding:12px;background:#F06A21;color:#1D1B18;border:0;cursor:pointer}@media print{button{display:none}main{margin:0;padding:0}section{break-inside:avoid}.slide{break-after:page}}'
def page(title,body):return f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{style}</style><main>{body}</main></html>'
palette=[('Mojo orange','#F06A21'),('Warm cream','#FFF8F0'),('Soft ink','#1D1B18'),('Sage','#A7B59E'),('Forest','#35594A')]
(out/'palette.css').write_text(':root {\n'+''.join(f'  --mojo-{name.lower().replace(" ","-")}: {hex};\n' for name,hex in palette)+'}\n')
(out/'quick-guide.html').write_text(page('Mojo quick brand guide','<small>MOJO / QUICK GUIDE / V0.2 · 6 OCTOBER 2026</small><h1>A little guidance.</h1><p>Palette approved. All other guidance proposed. Original mascot supplied; wordmark and other identity assets pending.</p><button onclick="window.print()">Print / save as PDF</button><section><h2>01 / Logo & mascot</h2><p>Use the untouched original. Never stretch, crop, recolour, or remove eye highlights. Original transparent mascot supplied; other identity files pending. Proposed clear space: ¼ artwork height; digital minimum: 32 px. Both require review.</p></section><section><h2>02 / Approved palette</h2>'+''.join(f'<p><b>{n}</b> {h}</p>' for n,h in palette)+'<p>Ink on cream, orange, or sage; cream on forest. Avoid white normal text on orange.</p></section><section><h2>03 / Typography · proposed</h2><p>Mojo Pixel Serif Draft v0.200 for main headings; Mojo Serif Refined v0.601 for subtitles. Supplied Inter v4.001 regular and italic for body and controls. Display 64/68; heading 40/44; body 14/23; caption 12/18 px.</p></section><section><h2>04 / Voice · proposed</h2><p>Warm, creative, community-oriented, casual, concise. Keep sentences short. Be accurate about features. Say what happened and the next useful step.</p></section>'))
slides=''.join(f'<section class="slide"><small>MOJO / {i+1:02} / PROPOSED</small><h1>{t}</h1><p>{d}</p>{extra}</section>' for i,(t,d,extra) in enumerate([('Room for a good idea.','Title slide · replace with approved title.',''),('One clear thought.','Content slide · add your three key points.','<ul><li>First point</li><li>Second point</li><li>Third point</li></ul>'),('Show the real thing.','Screenshot slide · insert current, privacy-safe product image.','<div style="background:#A7B59E;padding:90px;text-align:center">Screenshot not supplied</div>'),('Let the data speak.','Chart slide · replace with verified data and source.','<div style="border-left:2px solid #1D1B18;border-bottom:2px solid #1D1B18;height:200px;padding:20px">Chart area — no invented data</div>'),('Thanks for making space.','Closing slide · add a verified next step or contact.','')]))
(out/'slides.html').write_text(page('Mojo proposed presentation layouts','<button onclick="window.print()">Print slides / save as PDF</button><p>Editable HTML, not PowerPoint. Main headings use Mojo Pixel Serif Draft; subtitles use Mojo Serif Refined; body uses Inter. When opened outside the site, install authorized fonts locally or system fallbacks apply.</p>'+slides))
(out/'signature.html').write_text(page('Mojo proposed email signature','<small>PROPOSED / EDITABLE HTML SOURCE</small><section><b>Your name</b><br>Your role · Mojo<br><span style="color:#35594A">Add a verified email address and website.</span></section><p>Replace these fields before use. No contact information has been invented.</p>'))
font=root/'public/fonts/Inter-Variable.ttf'
# Variable distribution is not assumed: use a real installed regular face.
shutil.copyfile(font,out/'Inter-Variable.ttf')
shutil.copyfile(root/'public/fonts/Inter-Italic-Variable.ttf',out/'Inter-Italic-Variable.ttf')
(out/'inter-latin.woff2').unlink(missing_ok=True)
shutil.copyfile(root/'public/brand/mojo-cat-transparent.svg',out/'mojo-cat-transparent.svg')
shutil.copyfile(root/'node_modules/@fontsource/inter/LICENSE',out/'Inter-LICENSE.txt')
(out/'README.txt').write_text('Mojo Toolkit v0.2\nPalette values approved. All templates and guidance proposed.\nSVG: edit text and shapes in a vector editor. HTML: edit source in a text editor; browser print to PDF.\nInter: supplied variable regular and italic TTF v4.001, SIL OFL included.\nOriginal mascot SVG supplied and unchanged. Mojo Pixel Serif Draft v0.200 for main headings; Mojo Serif Refined v0.601 for subtitles. Custom fonts are used on the website but excluded from downloadable packs until download permission is confirmed. Portable SVG templates retain system font fallbacks. HTML downloads use site fonts online; extracted HTML uses system fallbacks unless fonts are installed and CSS paths adjusted.\nOriginal workspace scene: concept artwork created for this project.\n')
shutil.copyfile(root/'public/workspace-scene.svg',out/'workspace-scene.svg')
with zipfile.ZipFile(out/'mojo-starter-pack.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(out.iterdir()):
  if p.suffix!='.zip':z.write(p,p.name)
