export const meta={version:'0.1',updated:'6 October 2026',status:'Working draft'};
export const palette=[{name:'Mojo orange',hex:'#F06A21',role:'Our signature. Actions, highlights, and moments of energy.'},{name:'Warm cream',hex:'#FFF8F0',role:'Room to breathe. Main backgrounds and light surfaces.'},{name:'Soft ink',hex:'#1D1B18',role:'Clarity first. Text, headings, and outlines.'},{name:'Sage',hex:'#A7B59E',role:'A little softness. Supporting surfaces and illustrations.'},{name:'Forest',hex:'#35594A',role:'Depth and grounding. Dark sections and secondary actions.'}];
export const chapters=[
{id:'foundations',n:'01',title:'Brand foundations',short:'What makes us Mojo',description:'A shared starting point for how we show up.',items:[['Our personality','Warm, creative, community-oriented, casual, and concise. These are the intended qualities supplied for this toolkit.'],['Short description · proposed','Mojo brings a warm, creative spirit to its community.'],['Extended description · proposed','Mojo’s intended brand personality is casual and concise, with creativity and community at its heart. Product capabilities and audience claims still need an approved brief.']]},
{id:'logos',n:'02',title:'Logo & mascot',short:'A familiar face',description:'Use original artwork, every time.',items:[['Asset availability','The mascot, wordmark, combined logo, and app icon have not been supplied. No substitute artwork is presented as the Mojo logo.'],['Clear space · proposed','Reserve at least one quarter of the artwork height on all sides. Confirm this rule with the brand owner before production.'],['Minimum size · proposed','Start at 32 px for a digital mascot and check legibility in context. Print minimum sizes require an approved production proof.'],['Keep the original','Do not stretch, crop, recolour, add effects, or remove the white eye highlights. Preserve the exact supplied SVG geometry when it arrives.']]},
{id:'colour',n:'03',title:'Colour',short:'A palette with personality',description:'Five colours. Plenty of possibilities.',items:[]},
{id:'typography',n:'04',title:'Typography',short:'Words with warmth',description:'Expressive headlines. Effortless reading.',items:[['Mojo Serif · unavailable','No Mojo Serif files or version metadata were supplied. Georgia is the temporary heading fallback, not approved Mojo typography.'],['Inter · installed','Inter 5.2.8 package, locally served font files. Body, navigation, and interface labels. SIL Open Font License; license included in the resource pack.'],['Type scale · proposed','Display 64/68 px; headings 40/44 px; subheads 24/30 px; body 14/23 px; captions 12/18 px. Inter weights 400, 500, and 600. Heading fallback: Georgia, serif. Body fallback: Arial, sans-serif.']]},
{id:'voice',n:'05',title:'Voice & language',short:'Sound like a person',description:'Warm by default. Clear by design.',items:[['Marketing · proposed','Lead with one honest idea. Use short sentences and specific language. Avoid unsupported features, superlatives, and promises.'],['Product & support · proposed','Explain what happened and the next useful step. Be kind without over-apologizing. Never imply a task succeeded when it did not.'],['Community · proposed','Invite participation without pressure. Use humour sparingly; avoid slang that excludes people. Sentence case is the default. Confirm feature names before using them.']]},
{id:'templates',n:'06',title:'Templates',short:'A head start on making',description:'Editable starting points, ready for your next idea.',items:[]},
{id:'imagery',n:'07',title:'Imagery & motion',short:'Show the real thing',description:'Honest imagery, with a little imagination.',items:[['Product screenshots · proposed','Use current screens, remove personal information, and keep text readable. No product screenshots have been supplied.'],['Community photography · proposed','Use photos with documented permission and consent. No photography or usage releases have been supplied.'],['Pixel illustrations · proposed','Use consistent 8 px steps and flat palette-based shading. Keep decoration out of reading areas. The workspace scene here is original concept artwork.'],['Video & animation · proposed','Use readable captions and quiet overlays. Honour reduced motion. Mascot animation is unavailable; use the original static asset once supplied.']]},
{id:'components',n:'08',title:'Product components',short:'The little building blocks',description:'New concepts for a consistent interface.',items:[['Concepts, not existing product UI','No product component library was supplied. Every example here is proposed and requires product review.']]},
{id:'campus',n:'09',title:'Campus & merchandise',short:'Bring people together',description:'Practical starting points for moments in person.',items:[['Event checklist · proposed','Confirm venue, accessibility, hosts, permissions, registration route, signage, and the approved event description. Test the registration link before generating a QR code.'],['Run of show · proposed','−30 min: setup and sound check. 0: welcome. +10: activity introduction. +20: making and sharing. +50: wrap-up. +60: cleanup. Adjust to your event.'],['Merchandise · concept only','Sticker, shirt, hoodie, and tote applications are mockups. No production artwork, approved logo, garment specifications, or print separations are available.'],['Secondary resources','Business cards and meeting backgrounds can be added after approved identity assets are supplied.']]},
{id:'downloads',n:'10',title:'Quick guide & downloads',short:'Everything in one place',description:'Find a resource. Make it your own.',items:[]},
{id:'requests',n:'11',title:'Requests & updates',short:'Keep the toolkit growing',description:'A living resource, built together.',items:[['Request an asset','No contact address or submission service has been supplied. Copy the request brief below and send it through your team’s existing channel.'],['Changelog · 6 October 2026','v0.1 — Initial toolkit. Approved palette documented; proposed guidance and editable SVG / HTML starter layouts added. Official identity assets still pending.']]}
];
export const assets=[
...['Social announcement','Product demo','Creation spotlight','Creator recruitment','Campus event','Partnership brief'].map((name,i)=>({name,id:['social','demo','spotlight','recruitment','campus','partnership'][i],type:'Templates',format:'SVG',status:'Proposed',version:'0.1',use:'Editable starter layout',path:'/downloads/'+['social','demo','spotlight','recruitment','campus','partnership'][i]+'.svg'})),
{name:'Presentation slides',id:'slides',type:'Templates',format:'HTML',status:'Proposed',version:'0.1',use:'Five editable slide layouts; print to PDF',path:'/downloads/slides.html'},
{name:'Email signature',id:'signature',type:'Templates',format:'HTML',status:'Proposed',version:'0.1',use:'Editable HTML signature',path:'/downloads/signature.html'},
{name:'Quick brand guide',id:'guide',type:'Guides',format:'HTML',status:'Proposed',version:'0.1',use:'Print-friendly reference; palette approved',path:'/downloads/quick-guide.html'},
{name:'Core palette tokens',id:'palette',type:'Guides',format:'CSS',status:'Approved',version:'0.1',use:'Five approved colour values',path:'/downloads/palette.css'},
{name:'Inter regular font',id:'inter',type:'Fonts',format:'WOFF2',status:'Available',version:'5.2.8',use:'Latin regular 400 font · SIL OFL',path:'/downloads/inter-latin.woff2'},
...['Mojo mascot','Mojo wordmark','Combined logo','App icon','Mojo Serif'].map(name=>({name,id:name,type:name==='Mojo Serif'?'Fonts':'Logos',format:'Pending',status:'Unavailable',version:'—',use:'Awaiting original file',path:null}))];
export const requestBrief='Mojo asset request\nResource needed:\nAudience and intended use:\nFormat and dimensions:\nDeadline:\nCopy and approved claims:\nPermissions / approval owner:\nReference or issue details:';
