import './style.css';
import {brandSignature} from './brand.js';
import {startIntro} from './intro.js';
import {foundationsPage} from './foundations.js';
import {logoPage,colourPage,typographyPage} from './reference-pages.js';
import {meta,palette,chapters,assets,requestBrief,foundations,brandLine,customFonts,brandStatuses} from './content.js';
const icons={overview:'◫',foundations:'⌘',logos:'♧',colour:'◉',typography:'Tt',voice:'☷',templates:'▤',imagery:'▧',components:'▦',campus:'⚑',downloads:'↓',requests:'↗'};
let active='overview',query='',filter='All';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function luminance(h){let v=h.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722}
const ratio=(a,b)=>{let x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const badge=(s='Proposed')=>`<span class="badge ${s.toLowerCase()}">${esc(s)}</span>`;
const download=a=>a.path?`<a class="download" href="${a.path}" download aria-label="Download ${esc(a.name)}">Download ${a.format} <span>↓</span></a>`:`<span class="missing">${a.status==='Unavailable'?'File not supplied':'Download permission pending'}</span>`;
function colours(){return `<div class="swatches">${palette.map(p=>`<article class="swatch"><div class="paint" style="background:${p.hex}">${p.name==='Mojo orange'?'<span>Our signature</span>':''}</div><div class="swatch-info"><strong>${p.name}</strong><p class="swatch-role">${p.role}</p><button class="copy hex" data-copy="${p.hex}" aria-label="Copy ${p.name} HEX">${p.hex} <span>⧉</span></button></div></article>`).join('')}</div>`}
function assetCard(a){return `<article class="asset-card"><div class="asset-preview ${a.id}" aria-hidden="true">${a.id==='mascot'?`<img src="/brand/mojo-cat-transparent.svg" alt="" loading="lazy">`:a.path&&a.format==='SVG'?`<img src="${a.path}" alt="" loading="lazy">`:(a.path||a.type==='Fonts')?`<span class="mini-word">${a.type==='Fonts'?'Aa':a.type==='Guides'?'A little\nMojo.':'Make room\nfor ideas.'}</span><span class="mini-note">${a.format} / ${a.version}</span>`:'<span class="empty-symbol">Asset pending</span>'}</div><div class="asset-info"><div class="row">${badge(a.status)}<span class="technical">${a.format}</span></div><h3>${esc(a.name)}</h3><p>${esc(a.use)}</p>${download(a)}</div></article>`}
function overview(){return `<section class="hero courtyard-hero"><div class="scene hero-environment"><img class="courtyard-art" src="/courtyard.png" alt="Original pixel-art leafy courtyard with a shared worktable, notebook and orange accents"></div><div class="hero-copy"><h1>${brandLine.split('. ')[0]}.<br> ${brandLine.split('. ')[1]}</h1><p>Our shared reference for applying the brand,<br class="desktop"> finding assets, and building with consistency.</p><div class="actions"><a class="button primary" href="/downloads/mojo-starter-pack.zip" download>Download brand assets <span>↓</span></a><a class="button subtle" href="/downloads/quick-guide.html">View quick guide <span>↗</span></a></div><div class="hero-foot">An internal working resource for the Mojo team.</div></div><button class="ambient-toggle" aria-pressed="false" aria-label="Pause ambient motion">Pause motion</button><span class="ambient-steam" aria-hidden="true"><i></i><i></i><i></i></span></section><div class="toolkit-status"><span class="status-dot"></span><span>V${meta.version} · Working draft</span><span class="status-divider">/</span><span>Signature ${brandStatuses.signature.toLowerCase()}. Primary palette ${brandStatuses.primaryPalette.toLowerCase()}.</span><a href="#requests">Details ↗</a></div><section class="section-block"><div class="section-heading"><div><h2>Your next idea starts here.</h2></div><span class="muted">Less searching. More making.</span></div><div class="shortcut-grid">${[['logos','02','Logo & mascot','Meet the face of Mojo.','identity'],['templates','06','Ready-to-make templates','A head start, whatever you’re making.','template'],['typography','04','Type with personality','The right words. The right feel.','type'],['downloads','10','The quick brand guide','The essentials, all in one place.','guide']].map(([id,n,t,d,c])=>`<a class="shortcut ${c}" href="#${id}"><div class="shortcut-art">${c==='identity'?'<img class="mascot-shortcut" src="/brand/mojo-cat-transparent.svg" alt="Original Mojo cat mascot">':c==='template'?'<div class="paper"><small>MOJO / COMMUNITY</small><b>Good ideas.<br>Great company.</b></div>':c==='type'?'<span class="type-art">Aa<span>↗</span></span>':'<div class="guide-cover"><b>A little<br>guidance.</b></div>'}</div><div class="shortcut-text">${badge(c==='identity'?brandStatuses.signature:'Proposed')}<h3>${t} <span>↗</span></h3><p>${d}</p></div></a>`).join('')}</div></section><section class="section-block"><div class="section-heading"><div><h2>Warm. Grounded. Unmistakably Mojo.</h2></div><a class="text-link" href="#colour">Explore the palette ↗</a></div>${colours()}</section><section class="bottom-band"><div><h2>Find your starting point.</h2></div><div class="audiences">${['Team','Creators','Campus leads','Partners'].map((t,i)=>`<a href="#${['components','templates','campus','foundations'][i]}">${t} ↗</a>`).join('')}</div></section>`}
function catalogue(){let matches=assets.filter(a=>(filter==='All'||a.type===filter)&&`${a.name} ${a.use} ${a.status} ${a.format}`.toLowerCase().includes(query.toLowerCase()));return `<div class="catalogue-tools"><label class="asset-search">⌕ <input id="asset-search" placeholder="Search assets, formats, or status…" value="${esc(query)}" aria-label="Search assets"></label><div class="filters" role="group" aria-label="Asset type">${['All','Logos','Templates','Fonts','Guides'].map(t=>`<button class="filter ${t===filter?'selected':''}" data-filter="${t}">${t}</button>`).join('')}</div></div><p class="technical">${matches.length} RESOURCES · DOWNLOADS CONTAIN REAL FILES ONLY</p><div class="asset-grid">${matches.map(assetCard).join('')||'<p class="empty-state">No matching resources. Try another search or filter.</p>'}</div>`}
function chapter(c){if(c.id==='foundations')return foundationsPage(esc);if(c.id==='logos')return logoPage();if(c.id==='colour')return colourPage(colours);if(c.id==='typography')return typographyPage();let body=`<div class="guidance-grid">${c.items.map(([t,d])=>`<article class="guidance"><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('')}</div>`;
if(c.id==='voice')body+=`<div class="example-grid"><article class="guidance"><span class="technical">BEFORE · TOO FORMAL</span><h3>“We regret to inform you that the operation could not be completed.”</h3></article><article class="guidance"><span class="technical">AFTER · PROPOSED</span><h3>“That didn’t work. Please try again.”</h3><p>Use only when retrying is a valid next step.</p></article></div>`;
if(c.id==='templates')body=`<div class="notice"><p>All layouts are <strong>proposed</strong>. SVG files are editable in compatible vector editors. HTML sources are editable in a text editor. No PowerPoint or Figma files are claimed.</p></div><div class="template-example"><img src="/downloads/social.svg" alt="Proposed social announcement layout: Good ideas. Great company. With a labelled image placeholder."><div><span class="eyebrow">SOCIAL ANNOUNCEMENT / PROPOSED</span><h2>Give one idea<br>room to breathe.</h2><p>Use a large heading, a real image, and a short next step. Replace placeholder copy with approved information.</p><a class="button primary" href="/downloads/social.svg" download>Download editable SVG ↓</a></div></div><div class="asset-grid">${assets.filter(a=>a.type==='Templates').map(assetCard).join('')}</div>`;
if(c.id==='imagery')body+=`<img class="wide-scene" src="/workspace-scene.svg" alt="Original pixel workspace illustration"><p class="technical">ORIGINAL WORKSPACE CONCEPT · MASCOT AVAILABLE IN LOGO & MASCOT</p><div class="empty-state">Photography, product screenshots, and mascot animations: not supplied. Permissions: unknown until supplied and reviewed.</div>`;
if(c.id==='components')body+=`<div class="component-demo"><div><span class="technical">BUTTONS & INPUT</span><label for="idea">Name your idea</label><input id="idea" placeholder="A new beginning"><button class="button primary" id="demo-button">Try action ↗</button><p id="demo-feedback" role="status"></p></div><div><span class="technical">CHAT & EMPTY STATE</span><p class="chat">What would you like to make?</p><div class="empty-state">No creations yet. Start with an idea.</div><p class="loading"><span></span> Loading concept</p></div></div><div class="developer-notes"><div><span class="eyebrow">IMPLEMENTATION / PROPOSED</span><h2>Build from the shared tokens.</h2><p>Use the core palette and original mascot. These rendered examples are concepts, not an existing product library.</p><a class="text-link" href="https://github.com/ChenJiale1012/mojo-toolkit" target="_blank" rel="noopener">View the shared repository ↗</a></div><div><pre><code>&lt;button class="button primary"&gt;
  Download SVG
&lt;/button&gt;

.button.primary {
  background: var(--orange);
  color: var(--ink);
}</code></pre><button class="text-copy copy" data-copy="&lt;button class=&quot;button primary&quot;&gt;Download SVG&lt;/button&gt;">Copy button markup ⧉</button></div></div><div class="creation-grid">${['A gathering of good ideas','Notes from the studio','Something worth sharing'].map((s,i)=>`<article class="creation"><span class="technical">CREATION COVER CONCEPT ${i+1}</span><h3>${s}</h3>${i===0?badge('Proposed')+'<p>Mojo Recommended · proposed treatment</p>':''}</article>`).join('')}</div>`;
if(c.id==='campus')body+=`<div class="merch-grid">${['Sticker','Shirt','Hoodie','Tote'].map(t=>`<article class="merch"><img class="merch-mascot" src="/brand/mojo-cat-transparent.svg" alt=""><h3>${t}</h3><p>Concept surface only<br>Production artwork pending</p>${badge()}</article>`).join('')}</div><p>Poster and registration artwork: use the editable campus SVG. QR signage awaits a verified registration URL; no fake QR code is included.</p><a class="button primary" href="/downloads/campus.svg" download>Download campus layout ↓</a>`;
if(c.id==='downloads')body=`<div class="actions"><a class="button primary" href="/downloads/mojo-starter-pack.zip" download>Download starter pack ↓</a><a class="button subtle" href="/downloads/quick-guide.html">Open print-friendly guide ↗</a></div><p class="muted">Contains editable layouts, palette, guide, Inter font and license. Original mascot included. Wordmark, combined logo and app icon are pending. Supplied custom desktop TTF fonts and a usage guide are included.</p><div id="catalogue">${catalogue()}</div>`;
if(c.id==='requests')body+=`<div class="request"><h3>A useful brief goes a long way.</h3><pre>${esc(requestBrief)}</pre><button class="button primary copy" data-copy="${esc(requestBrief)}">Copy request brief ⧉</button><p class="muted">Copies text only. Nothing is submitted.</p></div><article class="guidance"><h3>Needed to finalize</h3><p>Wordmark, combined logo and app icon; custom font licence/readme files; approved product descriptions; imagery and licenses; contact mechanism; brand owner review of proposed rules.</p></article>`;
return `<div class="chapter-heading"><h1>${c.title}.</h1><p>${c.description}</p>${badge(c.id==='colour'?'Approved':'Proposed')}</div>${body}`}
function searchResults(s){let term=s.toLowerCase(),cs=chapters.filter(c=>(JSON.stringify(c)+(c.id==='foundations'?JSON.stringify(foundations):'')).toLowerCase().includes(term)),as=assets.filter(a=>`${a.name} ${a.use} ${a.format} ${a.status}`.toLowerCase().includes(term));return `<h1>Find your Mojo.</h1><p>Results for “${esc(s)}”</p><div class="search-results">${cs.map(c=>`<a href="#${c.id}"><span class="technical">GUIDANCE / ${c.n}</span><h3>${c.title} ↗</h3><p>${c.description}</p></a>`).join('')}${as.map(a=>`<div><span class="technical">RESOURCE / ${a.status}</span><h3>${a.name}</h3>${download(a)}</div>`).join('')}${!cs.length&&!as.length?'<p>No results. Try “colour”, “campus”, or “font”.</p>':''}</div>`}
function render(){let search=location.hash.startsWith('#search=')?decodeURIComponent(location.hash.slice(8)):null;active=search?'search':location.hash.slice(1)||'overview';let c=chapters.find(c=>c.id===active);document.title=`${c?.title||'Brand toolkit'} — Mojo`;document.querySelector('#app').innerHTML=`<a class="skip" href="#main">Skip to content</a><aside class="sidebar"><a class="wordmark" href="#overview" aria-label="Mojo toolkit home">${brandSignature()}</a><span class="sidebar-label">BRAND TOOLKIT</span><button id="mobile-menu" aria-expanded="false" aria-controls="navigation">Menu ☰</button><nav id="navigation" aria-label="Toolkit sections"><a href="#overview" class="nav-link ${active==='overview'?'active':''}" ${active==='overview'?'aria-current="page"':''}><span>${icons.overview}</span>Overview</a><p class="nav-group">THE BRAND</p>${chapters.slice(0,5).map(c=>nav(c)).join('')}<p class="nav-group">MAKE WITH MOJO</p>${chapters.slice(5,9).map(c=>nav(c)).join('')}<p class="nav-group">RESOURCES</p>${chapters.slice(9).map(c=>nav(c)).join('')}</nav><div class="sidebar-bottom"><span class="status-dot"></span> A living, growing toolkit<p>V${meta.version} · ${meta.updated}</p><a href="#requests">Help us make it better ↗</a></div></aside><div class="shell"><header class="topbar"><div><span>Mojo</span><span class="slash">/</span> Brand toolkit</div><form id="global-search"><label for="search-input" class="pixel-search-icon"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 2h7v2h2v7h-2v2H4v-2H2V4h2zm0 2v7h7V4zm9 8h2v2h2v2h2v3h-3v-2h-2v-2h-2z"/></svg></label><input id="search-input" aria-label="Search toolkit" placeholder="Search the toolkit" value="${esc(search||'')}"><button aria-label="Run search">↵</button></form><a href="/downloads/quick-guide.html" class="top-guide"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M2 3h6l2 2 2-2h6v13h-6l-2 2-2-2H2zM10 5v13"/></svg>Quick guide</a></header><main id="main" tabindex="-1">${search!==null?searchResults(search):active==='overview'?overview():c?chapter(c):'<h1>Section not found.</h1><a href="#overview">Back to overview</a>'}<footer><a class="footer-word" href="#overview" aria-label="Mojo toolkit home">${brandSignature()}</a><span>${brandLine}</span><span>WORKING DRAFT / V${meta.version}</span></footer></main></div><div id="toast" role="status" aria-live="polite"></div>`.replaceAll('↗','<svg class="inline-icon arrow" aria-hidden="true" viewBox="0 0 16 16"><path d="M3 13 13 3M4 3h9v9"/></svg>').replaceAll('✳','<svg class="inline-icon star" aria-hidden="true" viewBox="0 0 24 24"><path d="M12 1v22M1 12h22M4 4l16 16M4 20 20 4"/></svg>');accentHeadings();bind();measurePairings()}
function nav(c){return `<a href="#${c.id}" class="nav-link ${active===c.id?'active':''}" ${active===c.id?'aria-current="page"':''}><span aria-hidden="true">${icons[c.id]}</span>${c.title}</a>`}
function toast(t){let el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function bind(){document.querySelector('.ambient-toggle')?.addEventListener('click',e=>{const paused=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',paused);e.currentTarget.textContent=paused?'Resume motion':'Pause motion';document.querySelector('.courtyard-hero').classList.toggle('ambient-paused',paused)});document.querySelectorAll('[data-logo-bg]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.logo-specimen').style.background=b.dataset.logoBg;document.querySelectorAll('[data-logo-bg]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})}));document.querySelector('#global-search').onsubmit=e=>{e.preventDefault();location.hash='search='+encodeURIComponent(document.querySelector('#search-input').value.trim())};document.querySelector('#mobile-menu').onclick=e=>{let open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',open);document.querySelector('.sidebar').classList.toggle('open',open)};document.querySelector('#asset-search')?.addEventListener('input',e=>{query=e.target.value;refreshCatalogue()});document.querySelector('#demo-button')?.addEventListener('click',()=>document.querySelector('#demo-feedback').textContent='Example action complete. This is a UI concept.');}
function refreshCatalogue(){let el=document.querySelector('#catalogue');el.innerHTML=catalogue();let input=el.querySelector('input');input.focus();input.setSelectionRange(query.length,query.length);input.addEventListener('input',e=>{query=e.target.value;refreshCatalogue()})}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-copy]');if(b){try{await navigator.clipboard.writeText(b.dataset.copy);toast(b.classList.contains('hex')?'Colour copied':b.dataset.copy===brandLine?'Brand line copied':'Copied to clipboard')}catch{toast('Clipboard unavailable. Select and copy the displayed text.')}}let f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;refreshCatalogue()}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();startIntro();

function accentHeadings(){document.querySelectorAll('h1,h2,h3,.font-sample,.mini-word,.paper b,.guide-cover b,.type-example b').forEach(el=>{let walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(!node.textContent.includes('.'))continue;const fragment=document.createDocumentFragment();for(const part of node.textContent.split(/(\S*\.)/g)){if(!part)continue;if(part.endsWith('.')){let span=document.createElement('span');span.className='punctuated-word';span.append(document.createTextNode(part.slice(0,-1)));let dot=document.createElement('span');dot.className='title-period';dot.textContent='.';span.append(dot);fragment.append(span)}else fragment.append(document.createTextNode(part))}node.replaceWith(fragment)}})}
function measurePairings(){document.querySelectorAll('.pair').forEach(el=>{const css=getComputedStyle(el),hex=s=>'#'+s.match(/\d+/g).slice(0,3).map(n=>Number(n).toString(16).padStart(2,'0')).join('');const r=ratio(hex(css.color),hex(css.backgroundColor));el.querySelector('b').textContent=`${r.toFixed(2)}:1 · ${r>=4.5?'AA normal text':r>=3?'AA large text only':'Does not meet AA'}`})}
