import './style.css';
import './working-pages.css';
import './refinement.css';
import './palette.css';
import './key-guidance.css';
import {brandSignature} from './brand.js';
import {startIntro} from './intro.js';
import {courtyardScene,mountCourtyardMotion} from './scene.js';
import './scene.css';
import {foundationsPage} from './foundations.js';
import {logoPage,colourPage,typographyPage} from './reference-pages.js';
import {meta,palette,chapters,assets,foundations,brandLine,brandStatuses,templates} from './content.js';
import {copyButton,pixelIcon,searchControl,bindCopyControls,bindSearchControls} from './controls.js';
import {assetCard,colourCards,badge} from './ui.js';
import {voicePage,templatesPage,imageryPage,componentsPage,requestsPage,campusPage} from './working-pages.js';
const icons={overview:'◫',foundations:'⌘',logos:'♧',colour:'◉',typography:'Tt',voice:'☷',templates:'▤',imagery:'▧',components:'▦',campus:'⚑',downloads:'↓',requests:'↗'};
let active='overview',query='',filter='All',disposeScene=()=>{};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function luminance(h){let v=h.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722}
const ratio=(a,b)=>{let x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const download=a=>a.path?`<a class="download" href="${a.path}" download aria-label="Download ${esc(a.name)}">Download ${a.format} <span>↓</span></a>`:`<span class="missing">${a.status==='Unavailable'?'File not supplied':'Download permission pending'}</span>`;
function colours(){return colourCards(palette)}

function overview(){return `<section class="hero courtyard-hero" data-motion-scene><img class="hero-surface" src="/hero-surface.svg" alt="" aria-hidden="true" draggable="false">${courtyardScene()}<div class="hero-copy"><h1>Better Together</h1><p>Our shared reference for applying the brand,<br class="desktop"> finding assets, and building with consistency.</p><div class="actions"><a class="button primary" href="/downloads/mojo-starter-pack.zip" download>Download brand assets <span>↓</span></a><a class="button subtle" href="/downloads/quick-guide.html">View quick guide <span>↗</span></a></div><div class="hero-foot">An internal working resource for the Mojo team.</div></div><button class="ambient-toggle" data-motion-toggle aria-pressed="false" aria-label="Pause ambient motion">Pause motion</button></section><div class="toolkit-status"><span class="status-dot"></span><span>V${meta.version} · Working draft</span><span class="status-divider">/</span><span>Signature ${brandStatuses.signature.toLowerCase()}. Primary palette ${brandStatuses.primaryPalette.toLowerCase()}.</span><a href="#requests">Details ↗</a></div><section class="section-block"><div class="section-heading"><div><h2>Your next idea starts here.</h2></div><span class="muted">Less searching. More making.</span></div><div class="shortcut-grid">${[['logos','02','Logo & mascot','Meet the face of Mojo.','identity'],['templates','06','Templates','Five categories under development.','template'],['typography','04','Type with personality','The right words. The right feel.','type'],['downloads','10','The quick brand guide','The essentials, all in one place.','guide']].map(([id,n,t,d,c])=>`<a class="shortcut ${c}" href="#${id}"><div class="shortcut-art">${c==='identity'?'<img class="mascot-shortcut" src="/brand/mojo-cat-transparent.svg" alt="Original Mojo cat mascot">':c==='template'?pixelIcon('presentation'):c==='type'?'<span class="type-art">Aa<span>↗</span></span>':'<div class="guide-cover"><b>Mojo.<br>Better together.</b></div>'}</div><div class="shortcut-text">${badge(c==='identity'?brandStatuses.signature:c==='template'?brandStatuses.templates:'Proposed')}<h3>${t} <span>↗</span></h3><p>${d}</p></div></a>`).join('')}</div></section><section class="section-block"><div class="section-heading"><div><h2>Unmistakably Mojo.</h2></div><a class="text-link" href="#colour">Explore the palette ↗</a></div>${colours()}</section><section class="bottom-band"><div><h2>Find your starting point.</h2></div><div class="audiences">${['Team','Creators','Campus leads','Partners'].map((t,i)=>`<a href="#${['components','templates','campus','foundations'][i]}">${t} ↗</a>`).join('')}</div></section>`}
function catalogue(){let matches=assets.filter(a=>(filter==='All'||a.type===filter)&&`${a.name} ${a.use} ${a.status} ${a.format}`.toLowerCase().includes(query.toLowerCase()));return `<div class="catalogue-tools"><label class="asset-search">${pixelIcon('search')} <input id="asset-search" placeholder="Search assets, formats, or status…" value="${esc(query)}" aria-label="Search assets"></label><div class="filters" role="group" aria-label="Asset type">${['All','Logos','Fonts','Guides'].map(t=>`<button class="filter ${t===filter?'selected':''}" data-filter="${t}" aria-pressed="${t===filter}">${t}</button>`).join('')}</div></div><p class="technical">${matches.length} RESOURCES · DOWNLOADS CONTAIN REAL FILES ONLY</p><div class="asset-grid">${matches.map(assetCard).join('')||'<p class="empty-state">No matching resources. Try another search or filter.</p>'}</div>`}
function chapter(c){
 const pages={foundations:foundationsPage,logos:logoPage,colour:()=>colourPage(colours),typography:typographyPage,voice:voicePage,templates:templatesPage,imagery:imageryPage,components:componentsPage,requests:requestsPage,campus:campusPage};
 if(pages[c.id])return pages[c.id]();
 let body=`<div class="guidance-grid">${c.items.map(([t,d])=>`<article class="guidance"><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('')}</div>`;
 if(c.id==='downloads')body=`<div class="actions"><a class="button primary" href="/downloads/mojo-starter-pack.zip" download>Download starter pack ↓</a><a class="button subtle" href="/downloads/quick-guide.html">Open Quick Guide ↗</a></div><p class="muted">Includes the Quick Guide, palette, supplied cat SVG, TTF files and Inter’s licence. Templates are under development. Voice & language is ${brandStatuses.voice.toLowerCase()}.</p><div id="catalogue">${catalogue()}</div>`;
 return `<div class="chapter-heading"><h1>${c.title}.</h1><p>${c.description}</p>${badge()}</div>${body}`;
}
function searchResults(s){let term=s.toLowerCase(),cs=chapters.filter(c=>(JSON.stringify(c)+(c.id==='foundations'?JSON.stringify(foundations):'')).toLowerCase().includes(term)),ts=templates.filter(t=>`${t.name} ${t.description} under development`.toLowerCase().includes(term)),as=assets.filter(a=>`${a.name} ${a.use} ${a.format} ${a.status}`.toLowerCase().includes(term));return `<h1>Find your Mojo.</h1><p>Results for “${esc(s)}”</p><div class="search-results">${cs.map(c=>`<a href="#${c.id}"><span class="technical">GUIDANCE / ${c.n}</span><h3>${c.title} ↗</h3><p>${c.description}</p></a>`).join('')}${ts.map(t=>`<a href="#templates/${t.id}"><span class="technical">TEMPLATE CATEGORY / UNDER DEVELOPMENT</span><h3>${esc(t.name)} ↗</h3><p>${esc(t.description)}</p></a>`).join('')}${as.map(a=>`<div><span class="technical">RESOURCE / ${a.status}</span><h3>${a.name}</h3>${download(a)}</div>`).join('')}${!cs.length&&!as.length&&!ts.length?'<p>No results. Try “colour”, “campus”, or “font”.</p>':''}</div>`}
function render(){disposeScene();let search=location.hash.startsWith('#search=')?decodeURIComponent(location.hash.slice(8)):null;active=search!==null?'search':location.hash.slice(1).split('/')[0]||'overview';let c=chapters.find(c=>c.id===active);document.title=`${c?.title||'Brand toolkit'} — Mojo`;document.querySelector('#app').innerHTML=`<a class="skip" href="#main">Skip to content</a><aside class="sidebar"><span class="sidebar-label">BRAND TOOLKIT</span><nav id="navigation" aria-label="Toolkit sections"><a href="#overview" class="nav-link ${active==='overview'?'active':''}" ${active==='overview'?'aria-current="page"':''}><span>${icons.overview}</span>Overview</a><p class="nav-group">THE BRAND</p>${chapters.slice(0,5).map(c=>nav(c)).join('')}<p class="nav-group">MAKE WITH MOJO</p>${chapters.slice(5,9).map(c=>nav(c)).join('')}<p class="nav-group">RESOURCES</p>${chapters.slice(9).map(c=>nav(c)).join('')}</nav><div class="sidebar-bottom"><span class="status-dot"></span> A living, growing toolkit<p>V${meta.version} · ${meta.updated}</p><a class="sidebar-utility-link" href="#requests">Requests & updates ↗</a></div></aside><div class="shell"><header class="topbar"><a class="wordmark logo-home header-logo" href="#overview" aria-label="Mojo toolkit home">${brandSignature()}</a><button id="mobile-menu" aria-expanded="false" aria-controls="navigation">Menu ☰</button>${searchControl('global-search','search-input',search||'')}<a href="/downloads/quick-guide.html" class="top-guide"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M2 3h6l2 2 2-2h6v13h-6l-2 2-2-2H2zM10 5v13"/></svg>Quick guide</a></header><main id="main" tabindex="-1">${search!==null?searchResults(search):active==='overview'?overview():c?chapter(c):'<h1>Section not found.</h1><a href="#overview">Back to overview</a>'}<footer><a class="footer-word logo-home" href="#overview" aria-label="Mojo toolkit home">${brandSignature()}</a><span>${brandLine}</span><span>WORKING DRAFT / V${meta.version}</span></footer></main></div><div id="toast" role="status" aria-live="polite"></div>`.replaceAll('↗','<svg class="inline-icon arrow" aria-hidden="true" viewBox="0 0 16 16"><path d="M3 13 13 3M4 3h9v9"/></svg>').replaceAll('✳','<svg class="inline-icon star" aria-hidden="true" viewBox="0 0 24 24"><path d="M12 1v22M1 12h22M4 4l16 16M4 20 20 4"/></svg>');accentHeadings();bind();disposeScene=mountCourtyardMotion(document);measurePairings();let section=location.hash.split('/')[1];if(section){document.getElementById(section)?.scrollIntoView();document.getElementById(section)?.focus({preventScroll:true})}}
function nav(c){return `<a href="#${c.id}" class="nav-link ${active===c.id?'active':''}" ${active===c.id?'aria-current="page"':''}><span aria-hidden="true">${icons[c.id]}</span>${c.title}</a>`}
function toast(t){let el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function bind(){
 document.querySelectorAll('[data-logo-bg]').forEach(b=>b.addEventListener('click',()=>{const preview=document.querySelector('.logo-preview');preview.style.background=b.dataset.logoBg;preview.style.setProperty('--logo-wordmark-color',b.dataset.logoText);document.querySelector('[data-logo-preview-note]').textContent=b.dataset.logoText==='#FFF8F0'?'Use the cream wordmark on a Soft ink background.':'Use the dark logo on a light background.';document.querySelectorAll('[data-logo-bg]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})}));
 document.querySelector('#mobile-menu').onclick=e=>{let open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',open);document.querySelector('.sidebar').classList.toggle('open',open)};
 document.querySelector('#asset-search')?.addEventListener('input',e=>{query=e.target.value;refreshCatalogue()});
}
function refreshCatalogue(){let el=document.querySelector('#catalogue');el.innerHTML=catalogue();let input=el.querySelector('input');input.focus();input.setSelectionRange(query.length,query.length);input.addEventListener('input',e=>{query=e.target.value;refreshCatalogue()})}
bindCopyControls(document,toast);bindSearchControls(document);
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;refreshCatalogue()}});
window.addEventListener('hashchange',()=>{render();if(!location.hash.includes('/'))window.scrollTo(0,0)});render();startIntro();

function accentHeadings(){document.querySelectorAll('h1,h2,h3,.font-sample,.mini-word,.paper b,.guide-cover b,.type-example b').forEach(el=>{let walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(!node.textContent.includes('.'))continue;const fragment=document.createDocumentFragment();for(const part of node.textContent.split(/(\S*\.)/g)){if(!part)continue;if(part.endsWith('.')){let span=document.createElement('span');span.className='punctuated-word';span.append(document.createTextNode(part.slice(0,-1)));let dot=document.createElement('span');dot.className='title-period';dot.textContent='.';span.append(dot);fragment.append(span)}else fragment.append(document.createTextNode(part))}node.replaceWith(fragment)}})}
function measurePairings(){document.querySelectorAll('.pair').forEach(el=>{const css=getComputedStyle(el),hex=s=>'#'+s.match(/\d+/g).slice(0,3).map(n=>Number(n).toString(16).padStart(2,'0')).join('');const r=ratio(hex(css.color),hex(css.backgroundColor));el.querySelector('b').textContent=`${r.toFixed(2)}:1 · ${r>=4.5?'AA normal text':r>=3?'AA large text only':'Does not meet AA'}`})}
