import {brandLine,brandStatuses,assets,requestBrief,changeBrief,contactInstruction,completion,changelog} from './content.js';
import {brandSignature} from './brand.js';
import {copyButton,searchControl,escapeHtml as esc} from './controls.js';
import {pageIntro,badge,assetCard} from './ui.js';

export function voicePage(){
  return `${pageIntro('Voice & language','')}<section class="work-in-progress">${badge(brandStatuses.voice)}<div class="work-lines" aria-hidden="true"><span></span><span></span><span></span></div><p>We’re still shaping how Mojo sounds. Writing guidance and examples will be added here.</p><a class="text-link" href="#requests">Suggest something for this page ↗</a></section>`;
}
export function templatesPage(){
  return `${pageIntro('Templates','Choose a layout for the task, replace the bracketed placeholders, and share the real details.')}<div class="template-notice">${badge('Proposed')}<p>Layouts and the primary palette need approval. The cat + lowercase mojo arrangement is approved.</p><p>Open a template to edit its fields in your browser. HTML files embed the actual fonts and print to PDF; SVG sources keep editable text. Some vector editors discard embedded fonts—install the supplied TTFs and check the export.</p><a class="text-link" href="/downloads/mojo-fonts.zip" download>Download the font files ↓</a></div><div class="asset-grid template-inventory">${assets.filter(a=>a.type==='Templates').map(assetCard).join('')}</div>`;
}
export function imageryPage(){
  return `${pageIntro('Imagery & motion','Use a clear subject, leave room for words, and keep the pixels crisp.')}<div class="reference-title"><h2>The courtyard.</h2>${badge('Proposed guidance')}</div><figure class="imagery-lead visual-frame"><img src="/courtyard.png" alt="Full existing pixel-art courtyard, shared worktable, plants and cream buildings"><figcaption><strong>An existing illustration.</strong> The broader imagery system is still proposed.</figcaption></figure><div class="imagery-grid"><figure><div class="visual-frame courtyard-crop"><img src="/courtyard.png" alt="Tighter crop around the worktable and orange notebook"></div><figcaption><h2>Choose a subject.</h2><p>Crop around the table; keep the object you’re showing easy to recognize.</p></figcaption></figure><figure><div class="visual-frame composition-demo"><img src="/courtyard.png" alt="Courtyard positioned to leave quiet cream space for text"><div><span class="technical">COMPOSITION EXAMPLE</span><h3>[Your headline].</h3><p>[One short message]</p></div></div><figcaption><h2>Give words room.</h2><p>Keep text in quiet areas, away from detailed plants and objects.</p></figcaption></figure></div><div class="imagery-grid edge-and-motion"><figure><div class="visual-frame edge-detail"><img src="/courtyard.png" alt="Magnified foliage edge with small crisp pixels against cream"></div><figcaption><h2>Keep the edge crisp.</h2><p>Preserve the fine pixel clusters when resizing; avoid blur.</p></figcaption></figure><figure><div class="visual-frame motion-scene" data-motion-scene><img src="/courtyard.png" alt="Static courtyard with a restrained steam effect over the mug"><span class="ambient-steam" aria-hidden="true"><i></i><i></i><i></i></span><button class="ambient-toggle" data-motion-toggle aria-pressed="false" aria-label="Pause courtyard motion">Pause motion</button><span class="motion-static-note">Static view · reduced motion</span></div><figcaption><h2>A little movement.</h2><p>The existing mug steam stays small; pause it when you prefer.</p></figcaption></figure></div><aside class="animation-direction">${badge(brandStatuses.animations)}<p>Mascot animations are being prepared.</p><a class="text-link" href="#logos/animations">See Mojo animations ↗</a></aside>`;
}
function snippet(code,label){return `<details class="reuse-details"><summary>How to reuse it</summary><pre><code>${esc(code)}</code></pre>${copyButton(code,label)}</details>`}
export function componentsPage(){
  const logoCode="import {brandSignature} from './src/brand.js';\nimport './src/style.css';\n\ndocument.querySelector('#logo').innerHTML = brandSignature();";
  const buttonCode='<a class="button primary" href="/brand/mojo-cat-transparent.svg" download aria-label="Download cat SVG">Download cat SVG ↓</a>';
  const controlCode="import {copyButton,searchControl,bindCopyControls,bindSearchControls} from './src/controls.js';\nimport './src/style.css';\n\nconst root = document.querySelector('#controls');\nroot.innerHTML = searchControl('project-search','project-query')\n  + copyButton('Mojo. Better together.','Copy brand line');\nbindCopyControls(root, message => {\n  document.querySelector('#feedback').textContent = message;\n});\nbindSearchControls(root, term => {\n  location.hash = 'search=' + encodeURIComponent(term);\n});\n// Include <div id=\"feedback\" role=\"status\"></div>.";
  const cardCode="import {assetCard} from './src/ui.js';\nimport {assets} from './src/content.js';\nimport './src/style.css';\nimport './src/working-pages.css';\n\ndocument.querySelector('#asset').innerHTML =\n  assetCard(assets.find(asset => asset.id === 'mascot'));";
  return `${pageIntro('Reusable components','Use the working elements that already serve this toolkit.')}<p class="dependency-note">These examples share the site’s modules and styles. Keep the matching files from <code>src/</code> and supplied assets from <code>public/</code>; no framework is required.</p><section class="reuse-block"><div class="reuse-heading"><h2>Approved logo arrangement.</h2>${badge(brandStatuses.signature)}</div><p>Use the original cat followed by lowercase mojo in navigation and brand introductions.</p><div class="component-surface">${brandSignature()}</div>${snippet(logoCode,'Copy logo import')}</section><section class="reuse-block"><h2>Buttons and links.</h2><p>Use a link for a real destination or download; disable actions whose files are unavailable.</p><div class="component-surface button-states">${buttonCode}<a class="text-link" href="#typography">Get the font files ↗</a><button class="button subtle" disabled>Combined-logo file pending</button></div>${snippet(buttonCode,'Copy button markup')}<p class="muted">Depends on <code>src/style.css</code>, <code>src/working-pages.css</code>, and the original SVG in <code>public/brand/</code>.</p></section><section class="reuse-block"><h2>Search and copy.</h2><p>Use the same pixel controls to find guidance or copy exact text.</p><div class="component-surface reusable-controls">${searchControl('reuse-search','reuse-query')}${copyButton(brandLine,'Copy component brand line')}</div>${snippet(controlCode,'Copy control imports')}</section><section class="reuse-block"><h2>Asset card.</h2><p>Show an actual file with its preview, status, use, and working download.</p><div class="component-asset">${assetCard(assets.find(a=>a.id==='mascot'))}</div>${snippet(cardCode,'Copy asset card import')}</section>`;
}
function completionList(items){return `<ul class="completion-list">${items.map(item=>`<li><a href="${item.href}">${esc(item.name)} ↗</a><p>${esc(item.text)}</p></li>`).join('')}</ul>`}
export function requestsPage(){
  return `${pageIntro('Requests & updates','Request an asset, suggest a change, or see what still needs work.')}<div class="discord-contact"><span class="status-dot"></span><p>${contactInstruction}</p></div><div class="request-grid"><section class="request-panel"><h2>Request an asset.</h2><p>Tell us what you need, where it will be used, when you need it, and any relevant size or format.</p><pre>${esc(requestBrief)}</pre>${copyButton(requestBrief,'Copy request brief')}</section><section class="request-panel"><h2>Suggest a change.</h2><p>Include the page, what needs changing, and a screenshot if helpful.</p><pre>${esc(changeBrief)}</pre>${copyButton(changeBrief,'Copy change brief')}</section></div><p class="muted">Copy a message and post it in Discord. Nothing is submitted by this page.</p><section class="completion-section"><h2>What still needs work.</h2><div class="completion-grid"><section><h3>Proposed</h3><p>Existing material that needs approval.</p>${completionList(completion.proposed)}</section><section><h3>Incomplete</h3><p>Content, assets, or implementation still to come.</p>${completionList(completion.incomplete)}</section></div></section><section class="changelog-section"><h2>Recent changes.</h2><ol class="changelog">${changelog.map(change=>`<li><div class="change-meta"><time datetime="${change.date}">6 October 2026</time><span class="change-label">${change.label}</span>${change.commit?'':'<span class="local-label">Current update</span>'}</div><div><h3><a href="${change.href}">${esc(change.title)} ↗</a></h3><p>${esc(change.summary)}</p>${change.commit?`<a class="commit-link" href="https://github.com/ChenJiale1012/mojo-toolkit/commit/${change.commit}" target="_blank" rel="noopener">Recorded change ${change.commit} ↗</a>`:''}</div></li>`).join('')}</ol></section><div class="request-closing">Need an asset or spotted something to change? ${contactInstruction}</div>`;
}
