import {brandLine,brandStatuses,assets,requestBrief,changeBrief,contactInstruction,completion,changelog,templates,illustrations} from './content.js';
import {brandSignature} from './brand.js';
import {copyButton,pixelIcon,searchControl,escapeHtml as esc} from './controls.js';
import {pageIntro,badge,assetCard} from './ui.js';

export function voicePage(){
  return `${pageIntro('Voice & language','')}<section class="work-in-progress" aria-label="Work in progress"><h2>Work in progress.</h2><p>We’re still shaping how Mojo sounds. Writing guidance and examples will be added here.</p></section>`;
}
export function templatesPage(){
  return `${pageIntro('Templates','Five categories we’re developing for the team.')}<div class="template-categories">${templates.map(t=>`<article class="template-category" id="${t.id}" tabindex="-1"><div class="category-icon">${pixelIcon(t.icon)}</div><div class="category-content"><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p>${badge(brandStatuses.templates)}</div></article>`).join('')}</div>`;
}
export function imageryPage(){
  return `${pageIntro('Imagery & motion','We’re developing Mojo’s illustration and motion style. These images show the current direction.')}<div class="page-status">${badge(brandStatuses.imagery)}</div><div class="explorations">${illustrations.filter(i=>i.path).map(i=>`<figure><div class="visual-frame"><img src="${i.path}" alt="${esc(i.alt)}"></div><figcaption><h2>${esc(i.title)}</h2><p>Current exploration.</p></figcaption></figure>`).join('')}</div><section class="animation-direction"><div class="reference-title"><h2>Motion.</h2>${badge(brandStatuses.animations)}</div><a class="text-link" href="#logos/animations">See Mojo animations ↗</a></section>`;
}

export function campusPage(){
  return `${pageIntro('Campus & merchandise','Brand materials for campus events and merchandise.')}<section class="merchandise-section"><div class="reference-title"><h2>Merchandise.</h2>${badge('Production artwork pending.')}</div><p>Mojo Merch is in development.</p><div class="merchandise-cards">${[['Stickers','Small brand touchpoints for campus activities.'],['T-shirts','Team identity for events and shared moments.'],['Totes','Mojo in everyday routines.']].map(([title,text])=>`<article class="merchandise-card"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section><section class="event-checklist"><h2>Before your campus event.</h2><ul><li>Confirm the venue, accessibility, hosts, and permissions.</li><li>Check the event description, date, and registration route.</li><li>Test links before using a QR code.</li><li>Plan signage and confirm which brand assets are available.</li></ul><a class="text-link" href="#templates/event-posters">Event Posters ↗</a>${badge(brandStatuses.templates)}</section><p class="contact-footer">${contactInstruction}</p>`;
}

function snippet(code,label){return `<details class="reuse-details"><summary>How to reuse it</summary><pre><code>${esc(code)}</code></pre>${copyButton(code,label)}</details>`}
export function componentsPage(){
  const logoCode="import {brandSignature} from './src/brand.js';\nimport './src/style.css';\n\ndocument.querySelector('#logo').innerHTML = brandSignature();";
  const buttonCode='<a class="button primary" href="/brand/mojo-cat-transparent.svg" download aria-label="Download cat SVG">Download cat SVG ↓</a>';
  const controlCode="import {copyButton,searchControl,bindCopyControls,bindSearchControls} from './src/controls.js';\nimport './src/style.css';\n\nconst root = document.querySelector('#controls');\nroot.innerHTML = searchControl('project-search','project-query')\n  + copyButton('Mojo. Better together.','Copy brand line');\nbindCopyControls(root, message => {\n  document.querySelector('#feedback').textContent = message;\n});\nbindSearchControls(root, term => {\n  location.hash = 'search=' + encodeURIComponent(term);\n});\n// Include <div id=\"feedback\" role=\"status\"></div>.";
  const cardCode="import {assetCard} from './src/ui.js';\nimport {assets} from './src/content.js';\nimport './src/style.css';\nimport './src/working-pages.css';\n\ndocument.querySelector('#asset').innerHTML =\n  assetCard(assets.find(asset => asset.id === 'mascot'));";
  return `${pageIntro('Reusable components','Use the working elements that already serve this toolkit.')}<p class="dependency-note">These examples share the site’s modules and styles. Keep the matching files from <code>src/</code> and supplied assets from <code>public/</code>; no framework is required.</p><section class="reuse-block"><div class="reuse-heading"><h2>Approved logo arrangement.</h2>${badge(brandStatuses.signature)}</div><p>Use the original cat followed by lowercase mojo in navigation and brand introductions.</p><div class="component-surface">${brandSignature()}</div>${snippet(logoCode,'Copy logo import')}</section><section class="reuse-block"><h2>Buttons and links.</h2><p>Use a link for a real destination or download; disable actions whose files are unavailable.</p><div class="component-surface button-states">${buttonCode}<a class="text-link" href="#typography">Get the font files ↗</a><button class="button subtle" disabled>Combined-logo file pending</button></div>${snippet(buttonCode,'Copy button markup')}<p class="muted">Depends on <code>src/style.css</code>, <code>src/working-pages.css</code>, and the original SVG in <code>public/brand/</code>.</p></section><section class="reuse-block"><h2>Search and copy.</h2><p>Use the same pixel controls to find guidance or copy exact text.</p><div class="component-surface reusable-controls">${searchControl('reuse-search','reuse-query')}${copyButton(brandLine,'Copy component brand line')}</div>${snippet(controlCode,'Copy control imports')}</section><section class="reuse-block"><h2>Asset card.</h2><p>Show an actual file with its preview, status, use, and working download.</p><div class="component-asset">${assetCard(assets.find(a=>a.id==='mascot'))}</div>${snippet(cardCode,'Copy asset card import')}</section>`;
}
function completionList(items){return `<ul class="completion-list">${items.map(item=>`<li><a href="${item.href}">${esc(item.name)} ↗</a><p>${esc(item.text)}</p></li>`).join('')}</ul>`}
function changeEntries(items){return `${items.map(change=>`<li><div class="change-meta"><time datetime="${change.date}">${new Date(change.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}</time><span class="change-label">${change.label}</span>${change.commit?'':'<span class="local-label">Current update</span>'}</div><div><h3><a href="${change.href}">${esc(change.title)} ↗</a></h3><p>${esc(change.summary)}</p>${change.commit?`<a class="commit-link" href="https://github.com/ChenJiale1012/mojo-toolkit/commit/${change.commit}" target="_blank" rel="noopener">Recorded change ${change.commit} ↗</a>`:''}</div></li>`).join('')}`;}
export function requestsPage(){
  const ordered=[...changelog].sort((a,b)=>b.date.localeCompare(a.date));
  const recent=ordered.slice(0,5),older=ordered.slice(5);
  return `${pageIntro('Requests & updates','Request an asset, suggest a change, or see what still needs work.')}<div class="discord-contact"><span class="status-dot"></span><p>${contactInstruction}</p></div><div class="request-grid"><section class="request-panel"><h2>Request an asset.</h2><p>Tell us what you need, where it will be used, when you need it, and any relevant size or format.</p><pre>${esc(requestBrief)}</pre>${copyButton(requestBrief,'Copy request brief')}</section><section class="request-panel"><h2>Suggest a change.</h2><p>Include the page, what needs changing, and a screenshot if helpful.</p><pre>${esc(changeBrief)}</pre>${copyButton(changeBrief,'Copy change brief')}</section></div><p class="muted">Copy a message and post it in Discord. Nothing is submitted by this page.</p><section class="completion-section"><h2>What still needs work.</h2><div class="completion-grid"><section><h3>Proposed</h3><p>Existing material that needs approval.</p>${completionList(completion.proposed)}</section><section><h3>Incomplete</h3><p>Content, assets, or implementation still to come.</p>${completionList(completion.incomplete)}</section></div></section><section class="changelog-section"><h2>Recent changes.</h2><ol class="changelog">${changeEntries(recent)}</ol>${older.length?`<details class="older-updates"><summary>Older updates <span class="older-count">(${older.length})</span></summary><ol class="changelog" start="6">${changeEntries(older)}</ol></details>`:''}</section><div class="request-closing">${contactInstruction}</div>`;
}
